server:
  port: 8081
spring:
  application:
    name: CAR-ADMIN
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
  cache:
    cache-names: outLimit，notOutLimit
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
    type: caffeine
swagger:
  enable: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always