server:
  port: 8081
spring:
  application:
    name: CAR-ADMIN
  cloud:
    nacos:
      config:
        server-addr: 188.131.137.79:8848
      discovery:
        server-addr: 188.131.137.79:8848
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names: cars，customers
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
    type: caffeine
swagger:
  enable: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always